apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: openemr
  name: openemr
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deploymentconfig: openemr
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        deploymentconfig: openemr
    spec:
      containers:
      - args:
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql
              key: host
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql
              key: name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: username
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        - name: MYSQL_ROOT_PASS
          valueFrom:
            secretKeyRef:
              name: mysql
              key: root_password
        - name: OE_PASS
          value: "pass"
        - name: OE_USER
          value: "admin"
        - name: REDIS_SERVER
          value: "redis"
        image: "quay.io/openemr/openemr:latest"
        imagePullPolicy: ""
        name: openemr
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ssl/private
          name: sslvolume-private
        - mountPath: /etc/ssl/certs
          name: sslvolume-certs
        - mountPath: /etc/ssl/kube
          name: openemr-certs-1
          readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: openemr
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sslvolume-certs
        persistentVolumeClaim:
          claimName: sslvolume
      - name: sslvolume-private
        persistentVolumeClaim:
          claimName: sslvolume-private
      - name: openemr-certs-1
        secret:
          defaultMode: 420
          secretName: openemr-certs
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - openemr
      from:
        kind: ImageStreamTag
        name: openemr:5.0.2
    type: ImageChange
