apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: openemr
  name: openemr
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: openemr/openemr:5.0.2
    name: 5.0.2
    referencePolicy:
      type: Source
