kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: openemr
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
