apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: docker.io/mariadb:10.4
    name: "10.4"
    referencePolicy:
      type: Source
